# rust-app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bsky-service
  namespace: app  
spec:
  selector:
    app: bsky
  ports:
    - protocol: TCP
      port: 8080  # The port Kubernetes will expose
      targetPort: 8080  # The port your Rust app listens on
  type: ClusterIP
