# memgraph-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memgraph
  template:
    metadata:
      labels:
        app: memgraph
    spec:
      containers:
        - name: memgraph
          image: memgraph/memgraph:latest
          ports:
            - containerPort: 7687  # Default port for Memgraph
