
# memgraph-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: memgraph-service
  namespace: app
spec:
  selector:
    app: memgraph
  ports:
    - protocol: TCP
      port: 7687  
      targetPort: 7687  
    - protocol: TCP
      port: 3000  
      targetPort: 3000  
      nodePort: 3000

  type: NodePort
